name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd flask-weather-docker || git clone https://github.com/Vin22-03/Day_6_flask_weather_CICD.git flask-weather-docker && cd flask-weather-docker
          git pull origin main
          docker stop flask-weather || true
          docker rm flask-weather || true
          docker build -t flask-weather .
          docker run -d -p 80:5000 --name flask-weather flask-weather
